### ISSUE TITLE
Can't sign into Modrinth

### ISSUE THREAD

**Issue by Felitendo** [DIDIRUS4/AstralRinth#46] opened 2024-12-01 17:19 UTC
The Cloudflare Captcha isn't loading. Therefore I cannot sign into Modrinth

**Comment by DIDIRUS4** [comment] 2024-12-01 17:35
It will take time to understand what is breaking there, in fact, I didn't change the code logic of authorization and just applied their new changes to the main branch, prod to our main branch. Maybe somethere is broken for now

**Comment by DIDIRUS4** [comment] 2024-12-01 18:49
# Original product has same issues with modrinth services authentication
- Authorization does not work even with a captcha, the **Login** button is not executed correctly, the problem is on the Modrinth side - we are waiting for their correction. The changes were active (from the code/main & code/prod branch) at the time of taking the screenshot and writing this comment
![image](https://github.com/user-attachments/assets/df4bc2b4-58c3-42b0-a006-a08feaad2ec6)

**Comment by DIDIRUS4** [comment] 2024-12-26 17:35
Fixed in 0.9.2 from Modrinth and 0.9.201-dev from AstralRinth

**Closed by DIDIRUS4** 2024-12-26 17:35 UTC
