### ISSUE TITLE
Cannot launch an instance for 1.18 (Vanilla)

### ISSUE THREAD

**Issue by sepsol** [DIDIRUS4/AstralRinth#21] opened 2024-07-04 04:56 UTC
### Describe the bug

The crash logs are provided below:
https://mclo.gs/axNBcC4

### Steps to reproduce

Install 1.18 without any loaders and then try to run it.

### Expected behavior

To run without any issues.

### System information

- Windows 11 version 23H2 build 22631.3810
- AstralRinth version 0.7.209 (Beta)

**Comment by DIDIRUS4** [comment] 2024-07-04 11:13
This issue can't be reproduced. Please try installing the recommended Java versions and then retry.

I review stacktrace in error log and see `java.lang.NoSuchMethodError: 'void org.lwjgl.system.JNI.invokePPPV'`.
I believe this is a problem specific to your personal usage, rather than a public issue.

**Comment by sepsol** [comment] 2024-07-04 15:15
I'm double-checked but I still experience the issue. Here's a recording:
https://youtu.be/u9G2V8y840c

**Comment by DIDIRUS4** [comment] 2024-07-04 15:19
![image](https://github.com/DIDIRUS4/AstralRinth/assets/77334306/34d1573b-d86b-4bdb-9af7-f8186343458f)

Incompatible Java, try install [Adoptium Temurin](https://adoptium.net/marketplace/?os=windows&version=17)

**Comment by sepsol** [comment] 2024-07-04 17:12
Even with the [Adoptium Temurin 17.0.11+9 JRE (Windows x64)](https://adoptium.net/temurin/releases/?os=windows&version=17&arch=x64&package=jre) installed and selected, the game would still crash.

![image](https://github.com/DIDIRUS4/AstralRinth/assets/47871887/6fab165e-aaa9-4781-abf4-78f0145529af)

You can see lhe logs here:
https://mclo.gs/D4T3loy

**Comment by DIDIRUS4** [comment] 2024-07-04 18:21
### Preboot error response
```
[Render thread/INFO]: [STDERR]: [LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
```

### Possible solutions
- Try following the reasons and solutions steps. Perhaps this can help you resolve your situation.
- There should be no arguments in the Java settings. Use the standard launcher settings both in the settings and to override the instance settings.
- It seems like you're having problems with LWJGL. To fix this, try following the steps recommended by Java when launching the game. These recommendations are not from the launcher itself, launcher just trying to run the game process.

### If issue not resolved by these steps
- If the issue persists, you might want to search for information about LWJGL and Java on Google to see if there are any solutions or workarounds available.

**Closed** 2024-07-07 17:37 UTC
Labels: bug
